---
title: "cleaning_description"
author: "Lizette van Zyl"
date: "October 25, 2017"
output: word_document
---
## Questions about Brady and Li Paper

1. The observational unit of this article was deaths that resulted within 1 hour
of getting into an auto accident. The file that contains this information within the
yearly zipped file is the "person" data file.

2. Li and Brady constrained their data to the following:

- st_case:
- veh_no: 
- inj_sev: injury severity
```{r}
clean_yearly_person_file <- function(year) {
# 1. Read data in.
person_file <- paste0("data-raw/yearly_person_data/person_", year, ".csv")
df <- readr::read_csv(person_file)
# 2. Convert all column names to lowercase.
colnames(df) <- tolower(colnames(df))
df <- df %>%
# 3. Limit variables.
dplyr::select(st_case, veh_no, per_no, state, per_typ, lag_hrs, lag_mins,
inj_sev, age, alc_res, contains("drugres"), sex) %>%
# 4. Limit to relevant `per_typ` and `inj_sev` values, then remove those variables.
dplyr::filter(per_typ == 1 & inj_sev == 4) %>%
dplyr::select(-per_typ, -inj_sev) %>%
# 5. Create a `unique_id`. Note: to be unique, `year` needs to be pasted on.
tidyr::unite(unique_id, st_case, veh_no, per_no) %>%
dplyr::mutate(year = year,
unique_id = paste(unique_id, year, sep = "_")) %>%
# 6. Limit to study states and then remove the `state` variable.
dplyr::filter(state %in% c(6,
15,
17,
33,
44,
54)) %>%
dplyr::select(-state) %>%
# 7. Convert `sex` to a factor with levels "Male" and "Female".
dplyr::mutate(sex = ifelse(sex == 9, NA, sex),
sex = factor(sex, levels = c(1, 2),
labels = c("Male", "Female"))) %>%
# 8. Use measured alcohol blood level to create `Alcohol` (logical for whether
# alcohol was present). Then remove the `alc_res` variable.
dplyr::mutate(alc_res = ifelse(alc_res > 94, NA, alc_res / 10),
Alcohol = alc_res >= 0.01) %>%
dplyr::select(-alc_res) %>%
# 9. Specify missing values for the lag minutes.
dplyr::mutate(lag_mins = ifelse(lag_mins == 99, NA, lag_mins))
# 10. Save lag hours coded as missing as `NA`.
if(year <= 2008){
df <- df %>%
dplyr::mutate(lag_hrs = ifelse(lag_hrs %in% c(99, 999), NA, lag_hrs))
} else {
df <- df %>%
dplyr::mutate(lag_hrs = ifelse(lag_hrs == 999, NA, lag_hrs))
}

# 11. Limit to deaths within an hour of the accident then remove those variables.
df <- df %>%
dplyr::filter((lag_hrs < 1) | (lag_hrs == 1 & lag_mins == 0)) %>%
dplyr::select(-lag_hrs, -lag_mins)
# 12. Save age values coded as missing as `NA`.
if(year <= 2008){
df <- df %>%
dplyr::mutate(age = ifelse(age == 99, NA, age))
} else {
df <- df %>%
dplyr::mutate(age = ifelse(age %in% c(998, 999), NA, age))
}
# 13. Use age to create age categories and then remove `age` variable.
df <- df %>%
dplyr::mutate(agecat = cut(age, breaks = c(0, 25, 45, 65, 1000),
labels = c("< 25 years",
"25--44 years",
"45--64 years",
"65 years +"),
include.lowest = TRUE, right = FALSE)) %>%
dplyr::select(-age)
# 14. Gather all the columns with different drug listings (i.e., `drugres1`,
# `drugres2`, `drugres3`). Convert from the numeric code listings to
# drug categories.
gathered_df <- df %>%
tidyr::gather(drug_number, drug_type_raw, contains("drugres")) %>%
dplyr::mutate(drug_type = ifelse(drug_type_raw %in% 100:295,
"Narcotic", NA),
drug_type = ifelse(drug_type_raw %in% 300:395,
"Depressant", drug_type),
drug_type = ifelse(drug_type_raw %in% 400:495,
"Stimulant", drug_type),
drug_type = ifelse(drug_type_raw %in% 600:695,
"Cannabinoid", drug_type),
drug_type = ifelse(drug_type_raw %in% c(500:595, 700:996),
"Other", drug_type),
drug_type = ifelse(drug_type_raw == 1,
"None", drug_type),
drug_type = factor(drug_type)) %>%
dplyr::select(-drug_type_raw, -drug_number) %>%
# 15. Filter out any observations where both alcohol and drug data is missing.
dplyr::filter(!(is.na(Alcohol) & is.na(drug_type)))
# 16. Create a subset with only individuals with at least one non-missing
# listing for drugs. (Write a sentence or two for each step in this pipe chain.)
non_missing_drugs <- gathered_df %>%
filter(!is.na(drug_type)) %>%
group_by(unique_id, drug_type) %>%
summarize(has_drug = TRUE) %>%
ungroup() %>%
mutate(row_num = 1:n()) %>%
spread(drug_type, has_drug, fill = FALSE) %>%
select(-row_num)
# 17. Join this back into the full dataset. (Write a sentence or two for each
# step in this pipe chain.)
df <- df %>%
dplyr::select(-contains("drugres")) %>%
dplyr::full_join(non_missing_drugs, by = "unique_id") %>%
dplyr::select(-None) %>%
tidyr::gather(drug_type, positive_for_drug, Alcohol, Cannabinoid,
Depressant, Narcotic, Other, Stimulant) %>%
dplyr::mutate(drug_type = factor(drug_type)) %>%
unique()
return(df)
}
# 18. Iterate the clean_yearly_person_file function across study years to
# create and save a single dataset.
# Note: map_df() is similar to map(), but it binds elements of the
# list resulting from map() together. To understand this step, try
# running this code with map instead of map_df, check out documentation
# for map and map_df, and look at the map_df() function by typing
# `map_df` in your console.
clean_fars <- map_df(1999:2010, clean_yearly_person_file)
save(clean_fars, file = "data/clean_fars.RData")
```

1. A .csv file with raw FARS data for each year is saved in the “data-raw/yearly_person_data” directory as “person_[year].csv”. Since the working directory is the project directory, the person_file object gives the path to the raw data file for whatever year is entered in the year argument of the function. The raw data for a year is read into R with the read_csv function, which reads in a comma separated file as a tibble in R. The function takes the file path (person_file) as its first argument, and the raw data frame is saved as an object called df.

2.To reduce the issues that accompany upper/lower case matching for manipulation of the dataframe,
change all the column names in the original dataframe to lowercase letter.

3. Reduce the number of columns (variables) that the data manipulation has to handle. Do this by selecting only the columns related to driver deaths within 1 hour of an accident in the 6 states that the analysis considers, as well as unique identification for the person, drug and alcohol test results, and timestamp information.

4. Limit severity of injury to "fatal injury" and limit the person type to those who were inside the vehicle (driving) only, excluding people that died as a result of being hit by a car/vehicle. After limiting the scope of the person and injury data, these two variables are removed from the dataset to simplify the later analysis, since there is only one "level" now for each of these, and there is no need to have the information repeated across all the other variables.

5. 

5. 