---
title: "fars_analysis"
author: "Lizette van Zyl"
date: "October 25, 2017"
output: word_document
---
```{r}
library(tidyverse)
library(ggplot2)
library(ggthemes)
```

```{r}
# table of clean-fars data

clean_fars %>%
  mutate(year_cat = cut(year, breaks = c(1999, 2002, 2006, 2010),
                        labels = c("1999-2002", "2003-2006",
                                   "2007-2010"),
                        include.lowest = TRUE, right = TRUE)) %>%
  filter(!is.na(sex)) %>%
  group_by(drug_type, sex, year_cat) %>%
  summarize(n_non_missing = sum(!is.na(positive_for_drug)),
            positive_test = sum(positive_for_drug, na.rm = TRUE),
            perc_positive = round(100 * positive_test / n_non_missing, 1)) %>%
  select(drug_type, sex, year_cat, perc_positive) %>%
  unite(sex_year_cat, sex, year_cat) %>%
  spread(sex_year_cat, perc_positive) %>%
  knitr::kable(col.names = c("Drug type", "F 1999-2002",
                             "F 2003-2006", "F 2007-2010",
                             "M 1999-2002", "M 2003-2006",
                             "M 2007-2010"))
```

```{r}
# first plot
fars_nums <- clean_fars %>%
             filter(!as.character(drug_type) %in% "Alcohol",
             !is.na(agecat)) %>%
             group_by(year, agecat, unique_id) %>%
             summarize(positive_test = any(positive_for_drug, na.rm = TRUE)) %>%
                       # n_non_missing = sum(!is.na(positive_for_drug)),
                       #positive_test = sum(positive_for_drug, na.rm = TRUE),
             ungroup() %>%
             group_by(year, agecat) %>%
             summarise(perc_positive = mean(positive_test)*100)
                    # round(100 * positive_test / n_non_missing, 1)) %>%
             # summarize(perc_positive = sum(perc_positive))

ggplot(fars_nums, aes(x = year, y = perc_positive, shape = agecat)) +
  geom_point() +
  geom_line()+
  theme_bw() +
  scale_y_continuous(limits = c(0, 30))
  
```

```{r}
# second plot
fars_nums2 <- clean_fars %>%
             filter(!as.character(drug_type) %in% "Alcohol") %>%
             group_by(year, drug_type) %>%
             summarize(n_non_missing = sum(!is.na(positive_for_drug)),
                       positive_test = sum(positive_for_drug, na.rm = TRUE),
                       perc_positive = round(100 * positive_test / n_non_missing, 1))

ggplot(fars_nums2, aes(x = year, y = perc_positive, shape = drug_type)) +
  geom_point() +
  geom_line()
```

```{r}
# plot 3
fars_nums3 <- clean_fars %>%
             filter(as.character(drug_type) %in% "Cannabinoid",
                    !is.na(agecat)) %>%
             group_by(year, agecat) %>%
             # distinct(unique_id) %>%
             summarize(n_non_missing = sum(!is.na(positive_for_drug)),
                       positive_test = sum(positive_for_drug, na.rm = TRUE),
                       perc_positive = round(100 * positive_test / n_non_missing, 1)) 


ggplot(fars_nums3, aes(x = year, y = perc_positive, shape = agecat)) +
  geom_point() +
  geom_line()
```

